version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: movieuser
      POSTGRES_PASSWORD: moviepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://movieuser:moviepassword@postgres:5432/moviedb
      - JWT_SECRET=your_jwt_secret_here
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    depends_on:
      - postgres
      - mailhog
    command: sh -c "npx prisma generate && npx prisma db push && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
