FROM node:18-alpine

WORKDIR /app

RUN corepack enable
RUN apk add --no-cache git

COPY package.json ./
RUN yarn install

COPY . .

RUN yarn build

EXPOSE 5173

CMD ["yarn", "preview", "--port", "5173", "--host"]
